[package]
name = "tv-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.7", default-features = false, features = ["json", "form", "http1", "tokio", "query"] }
hyper = { version = "0.14", default-features = false, features = ["http1", "server", "tcp"] }
jni = { version = "0.21.1", default-features = false, features = ["invocation"] }
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time"] }
base64 = "0.21"
parking_lot = "0.12"
